spring.application.name=back
server.port=8080
spring.config.import=optional:classpath:application-secret.properties

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/moviedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# JSON 출력 시 null 필드 제외
spring.jackson.default-property-inclusion=non_null
